export const FICHAPERSONAL_LABELS = {
	INFORMACION_PERSONA: 'Información persona',
	NOMBRE: 'Nombre completo',
	COD_EMPLEADO: 'documento identidad',
	COMPANIA: 'Compañía',
	MODALIDAD: 'Modalidad',
	INTENSIDAD_HORAS: 'Intensidad horas',
	COSTE: 'Coste',
	MONEDA: 'Moneda',
	ENTE_INSTRUCTOR: 'Ente instructor',
	CONOCIMIENTOS_ASOCIADOS: 'Conocimientos asociados',
	NOMBRES: 'Nombres',
	APELLIDOS: 'Apellidos',
	IDENTIFICACION: 'Identificación',
	PAIS: 'País',
	PROVINCIA: 'Provincia',
	EMAIL: 'Email',
	INFORMACION: 'Información',
	CONOCIMIENTOS: 'Conocimientos',
	CERTIFICACIONES: 'Certificaciones',
	TITULOS: 'Títulos',
	IDIOMAS: 'Idiomas',
	EXPORTAR: {
		CONOCIMIENTOS: 'Exportar conocimientos',
		CERTIFICACIONES: 'Exportar certificaciones',
		TITULOS: 'Exportar títulos',
		IDIOMAS: 'Exportar idiomas'
	},
	INFORMACION_CUENTA: 'Información cuenta',
	FUNCION_PRINCIPAL: 'Función principal',
	IDIOMA_NATIVO: 'Idioma nativo'
};
